### ISSUE TITLE
Paper example on how to use surface2hasc doesn't match code class names in surface directory anymore

### ISSUE THREAD

**Issue by arkanoid87** [ldesousa/hex-utils#35]
I've been trying to run some surface generator classes without success.
Can you please provide a brief example on how to use them?

Thank you

Last test
```
$ python3.6 /usr/local/bin/surface2hasc -x 0 -y 0 -X 2000 -Y 2000 -s 19.6 -m /usr/local/lib/python3.6/dist-packages/surfaces/pitGaussian.py -f Gaussian -o gaussian.hasc

TypeError: '<' not supported between instances of 'float' and 'Gaussian'
```

**Comment by ldesousa** [comment]
You can't do that from the command line, you'll have to code a small Python programme. Or use the interactive Python shell. The programme would look something like this:
```
import numpy as np
from surfaces.pitGaussian import Gaussian
g = Gaussian()
g.widenning = 2
g.plotWireFrame()
```

**Comment by arkanoid87** [comment]
Thanks! Closing
