### ISSUE TITLE
saveAsGeoJSON converts all values to strings

### ISSUE THREAD

**Issue by arkanoid87** [ldesousa/hex-utils#40]
the resulting geojson stores hasc values as strings instead of original numerical values

**Comment by ldesousa** [comment]
[JSON](https://www.json.org/json-en.html) is a human-readable text format. Or do I misinterpret your remark?

**Comment by arkanoid87** [comment]
by [RFC](https://tools.ietf.org/html/rfc8259) JSON includes strings and numbers

even if source HASC _mesh attribute contains only numbers, [saveAsGeoJSON writes them as strings inside the final json](https://github.com/ldesousa/hex-utils/blob/02ed9cc69353c33afd49a81aa68cdf408cd6b015/hex_utils/hasc.py#L205)

by opening the generated JSON with QGIS, you can see that the value field has type string but contains numbers only

[ESRI ASCII format contains only numerical data](http://resources.esri.com/help/9.3/arcgisengine/java/GP_ToolRef/spatial_analyst_tools/esri_ascii_raster_format.htm), but it might be limiting to assume just that as (geo)JSON is capable of storing string values also.

An idea could be to assign a type to the hasc and assume that on conversion, or just check the type of each element in _mesh when writing

**Comment by ldesousa** [comment]
I see now, you refer to the attributes of the Features, not the Features themselves. Indeed would be better to encode them as the numbers they are. Will look into it.
